FROM node:18-alpine
RUN apk add --no-cache git

WORKDIR /base/storage-subgraph

RUN git clone --depth 1 --branch <specific-tag> https://github.com/RequestNetwork/storage-subgraph /base/storage-subgraph \
    && cd /base/storage-subgraph \
    && git verify-commit HEADRUN npm -g install @graphprotocol/graph-cli
RUN yarn
RUN yarn codegen subgraph-private.yaml

#CMD yarn create-local ; yarn deploy-local ./subgraph-private.yaml

CMD graph create --node http://graph-node:8020/ RequestNetwork/request-storage && graph deploy --node http://graph-node:8020/ --ipfs http://ipfs:5001 --version-label $(git rev-parse --short HEAD) RequestNetwork/request-storage ./subgraph-private.yaml