/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import { Provider } from '@ethersproject/providers';
import type { AggregatorFraction, AggregatorFractionInterface } from '../AggregatorFraction';

const _abi = [
  {
    inputs: [],
    name: 'decimals',
    outputs: [
      {
        internalType: 'uint8',
        name: '',
        type: 'uint8',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'latestAnswer',
    outputs: [
      {
        internalType: 'int256',
        name: '',
        type: 'int256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'latestTimestamp',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];

export class AggregatorFraction__factory {
  static readonly abi = _abi;
  static createInterface(): AggregatorFractionInterface {
    return new utils.Interface(_abi) as AggregatorFractionInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): AggregatorFraction {
    return new Contract(address, _abi, signerOrProvider) as AggregatorFraction;
  }
}
