/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import { Provider } from '@ethersproject/providers';
import type { ERC20fraction, ERC20fractionInterface } from '../ERC20fraction';

const _abi = [
  {
    inputs: [],
    name: 'decimals',
    outputs: [
      {
        internalType: 'uint8',
        name: '',
        type: 'uint8',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];

export class ERC20fraction__factory {
  static readonly abi = _abi;
  static createInterface(): ERC20fractionInterface {
    return new utils.Interface(_abi) as ERC20fractionInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ERC20fraction {
    return new Contract(address, _abi, signerOrProvider) as ERC20fraction;
  }
}
