// @generated
// This file is @generated by prost-build

/// A single payment event from the ERC20FeeProxy contract
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Payment {
    /// The token contract address (TRC20)
    #[prost(string, tag = "1")]
    pub token_address: ::prost::alloc::string::String,
    /// The recipient address
    #[prost(string, tag = "2")]
    pub to: ::prost::alloc::string::String,
    /// The payment amount (as string to preserve precision)
    #[prost(string, tag = "3")]
    pub amount: ::prost::alloc::string::String,
    /// The indexed payment reference (hex encoded)
    #[prost(string, tag = "4")]
    pub payment_reference: ::prost::alloc::string::String,
    /// The fee amount (as string to preserve precision)
    #[prost(string, tag = "5")]
    pub fee_amount: ::prost::alloc::string::String,
    /// The fee recipient address
    #[prost(string, tag = "6")]
    pub fee_address: ::prost::alloc::string::String,
    /// The sender address (msg.sender)
    #[prost(string, tag = "7")]
    pub from: ::prost::alloc::string::String,
    /// Block number where the event was emitted
    #[prost(uint64, tag = "8")]
    pub block: u64,
    /// Block timestamp (Unix timestamp in seconds)
    #[prost(uint64, tag = "9")]
    pub timestamp: u64,
    /// Transaction hash
    #[prost(string, tag = "10")]
    pub tx_hash: ::prost::alloc::string::String,
    /// The proxy contract address that emitted the event
    #[prost(string, tag = "11")]
    pub contract_address: ::prost::alloc::string::String,
}

/// Collection of payment events
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Payments {
    #[prost(message, repeated, tag = "1")]
    pub payments: ::prost::alloc::vec::Vec<Payment>,
}
