import { ExtensionTypes } from '.';

/**
 * List of payment networks available (abstract the extensions type)
 * See also `TypesUtils.isPaymentNetworkId()` to match values from Extension.ID.
 * */
export const {
  PAYMENT_NETWORK_BITCOIN_ADDRESS_BASED: BITCOIN_ADDRESS_BASED,
  PAYMENT_NETWORK_TESTNET_BITCOIN_ADDRESS_BASED: TESTNET_BITCOIN_ADDRESS_BASED,
  PAYMENT_NETWORK_ERC20_ADDRESS_BASED: ERC20_ADDRESS_BASED,
  PAYMENT_NETWORK_ERC20_PROXY_CONTRACT: ERC20_PROXY_CONTRACT,
  PAYMENT_NETWORK_ERC20_FEE_PROXY_CONTRACT: ERC20_FEE_PROXY_CONTRACT,
  PAYMENT_NETWORK_ERC777_STREAM: ERC777_STREAM,
  PAYMENT_NETWORK_ETH_INPUT_DATA: ETH_INPUT_DATA,
  PAYMENT_NETWORK_ETH_FEE_PROXY_CONTRACT: ETH_FEE_PROXY_CONTRACT,
  PAYMENT_NETWORK_NATIVE_TOKEN: NATIVE_TOKEN,
  PAYMENT_NETWORK_ANY_TO_NATIVE_TOKEN: ANY_TO_NATIVE,
  PAYMENT_NETWORK_ANY_DECLARATIVE: DECLARATIVE,
  PAYMENT_NETWORK_ANY_TO_ERC20_PROXY: ANY_TO_ERC20_PROXY,
  PAYMENT_NETWORK_ANY_TO_ETH_PROXY: ANY_TO_ETH_PROXY,
} = ExtensionTypes.ID;
