/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from 'ethers';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';
import { TypedEventFilter, TypedEvent, TypedListener } from './commons';

interface DiamondNativeHashFacetInterface extends ethers.utils.Interface {
  functions: {
    'getNativeTokenHash()': FunctionFragment;
    'updateNativeTokenHash(address)': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'getNativeTokenHash', values?: undefined): string;
  encodeFunctionData(functionFragment: 'updateNativeTokenHash', values: [string]): string;

  decodeFunctionResult(functionFragment: 'getNativeTokenHash', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'updateNativeTokenHash', data: BytesLike): Result;

  events: {};
}

export class DiamondNativeHashFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DiamondNativeHashFacetInterface;

  functions: {
    getNativeTokenHash(overrides?: CallOverrides): Promise<[string]>;

    updateNativeTokenHash(
      _nativeTokenHash: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;
  };

  getNativeTokenHash(overrides?: CallOverrides): Promise<string>;

  updateNativeTokenHash(
    _nativeTokenHash: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    getNativeTokenHash(overrides?: CallOverrides): Promise<string>;

    updateNativeTokenHash(_nativeTokenHash: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getNativeTokenHash(overrides?: CallOverrides): Promise<BigNumber>;

    updateNativeTokenHash(
      _nativeTokenHash: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getNativeTokenHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateNativeTokenHash(
      _nativeTokenHash: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;
  };
}
