/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from 'ethers';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';
import { TypedEventFilter, TypedEvent, TypedListener } from './commons';

interface Test2FacetInterface extends ethers.utils.Interface {
  functions: {
    'test2Func1()': FunctionFragment;
    'test2Func10()': FunctionFragment;
    'test2Func11()': FunctionFragment;
    'test2Func12()': FunctionFragment;
    'test2Func13()': FunctionFragment;
    'test2Func14()': FunctionFragment;
    'test2Func15()': FunctionFragment;
    'test2Func16()': FunctionFragment;
    'test2Func17()': FunctionFragment;
    'test2Func18()': FunctionFragment;
    'test2Func19()': FunctionFragment;
    'test2Func2()': FunctionFragment;
    'test2Func20()': FunctionFragment;
    'test2Func3()': FunctionFragment;
    'test2Func4()': FunctionFragment;
    'test2Func5()': FunctionFragment;
    'test2Func6()': FunctionFragment;
    'test2Func7()': FunctionFragment;
    'test2Func8()': FunctionFragment;
    'test2Func9()': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'test2Func1', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func10', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func11', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func12', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func13', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func14', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func15', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func16', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func17', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func18', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func19', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func2', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func20', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func3', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func4', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func5', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func6', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func7', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func8', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test2Func9', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'test2Func1', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func10', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func11', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func12', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func13', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func14', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func15', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func16', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func17', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func18', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func19', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func2', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func20', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func3', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func4', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func5', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func6', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func7', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func8', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test2Func9', data: BytesLike): Result;

  events: {};
}

export class Test2Facet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>,
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: Test2FacetInterface;

  functions: {
    test2Func1(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func10(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func11(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func12(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func13(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func14(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func15(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func16(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func17(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func18(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func19(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func2(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func20(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func3(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func4(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func5(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func6(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func7(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func8(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    test2Func9(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;
  };

  test2Func1(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func10(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func11(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func12(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func13(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func14(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func15(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func16(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func17(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func18(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func19(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func2(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func20(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func3(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func4(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func5(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func6(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func7(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func8(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  test2Func9(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    test2Func1(overrides?: CallOverrides): Promise<void>;

    test2Func10(overrides?: CallOverrides): Promise<void>;

    test2Func11(overrides?: CallOverrides): Promise<void>;

    test2Func12(overrides?: CallOverrides): Promise<void>;

    test2Func13(overrides?: CallOverrides): Promise<void>;

    test2Func14(overrides?: CallOverrides): Promise<void>;

    test2Func15(overrides?: CallOverrides): Promise<void>;

    test2Func16(overrides?: CallOverrides): Promise<void>;

    test2Func17(overrides?: CallOverrides): Promise<void>;

    test2Func18(overrides?: CallOverrides): Promise<void>;

    test2Func19(overrides?: CallOverrides): Promise<void>;

    test2Func2(overrides?: CallOverrides): Promise<void>;

    test2Func20(overrides?: CallOverrides): Promise<void>;

    test2Func3(overrides?: CallOverrides): Promise<void>;

    test2Func4(overrides?: CallOverrides): Promise<void>;

    test2Func5(overrides?: CallOverrides): Promise<void>;

    test2Func6(overrides?: CallOverrides): Promise<void>;

    test2Func7(overrides?: CallOverrides): Promise<void>;

    test2Func8(overrides?: CallOverrides): Promise<void>;

    test2Func9(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    test2Func1(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func10(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func11(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func12(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func13(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func14(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func15(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func16(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func17(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func18(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func19(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func2(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func20(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func3(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func4(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func5(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func6(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func7(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func8(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test2Func9(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;
  };

  populateTransaction: {
    test2Func1(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func10(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func11(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func12(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func13(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func14(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func15(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func16(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func17(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func18(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func19(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func2(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func20(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func3(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func4(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func5(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func6(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func7(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func8(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    test2Func9(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;
  };
}
