name: Auto approve dependabot
on: pull_request

jobs:
  aprove:
    runs-on: ubuntu-latest
    steps:
    - name: 'Wait for status checks'
      id: waitforstatuschecks
      uses: "WyriHaximus/github-action-wait-for-status@0.1.0"
      with:
        ignoreActions: aprove
        checkInterval: 60
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - uses: hmarr/auto-approve-action@v2.0.0
      if: steps.waitforstatuschecks.outputs.status == 'success' && (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
