name: Auto Add to Project

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  add-to-project:
    uses: RequestNetwork/.github/.github/workflows/add-to-project.yml@main
    secrets:
      PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
